name: (GKE) Cleanup Galaxy and cluster on Google Kubernetes Engine
on:
  workflow_dispatch:
    inputs:
      clustername:
        description: 'Name of Kubernetes cluster'
        required: true
        default: 'gxy-on-demand'
jobs:
  cleanup:
    env:
      GKE_ZONE: us-east1-b
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Delete the GKE cluster
        continue-on-error: true
        run: gcloud container clusters delete "${{ github.event.inputs.clustername }}" --zone "$GKE_ZONE" --quiet
      - name: Delete the two GCP Disks for first Galaxy
        run: gcloud compute disks delete "${{ github.event.inputs.clustername }}-postgres-pd" --zone "$GKE_ZONE" --quiet && gcloud compute disks delete "${{ github.event.inputs.clustername }}-nfs-pd" --zone "$GKE_ZONE" --quiet
